In [2]:
import numpy as np
from mpl_toolkits import mplot3d
import open3d as o3d
import glob
import os
import os.path
import statistics as stats
from operator import itemgetter

ModuleNotFoundError: No module named 'open3d'

# Linear Sliceing Method
## Sort by Y

In [ ]:
# Testing Ground
plant = 'plant3_bb_sim.ply'
# Slicing out a portion

# Read .ply file
pcd_whole = o3d.io.read_point_cloud(plant)
ar_whole_field = np.asarray(pcd_whole.points)

type(ar_whole_field)

In [5]:
linear_matrix = []

intermed_list = []

a = ar_whole_field[0][0]

for i in ar_whole_field:
    print(i[0])
    if abs(i[0] - a) < 10:
        intermed_list.append(list(i))

        a = i[0]

        print(f'Building intermed list: {len(intermed_list)}')



    
    else:
        pcd_slice = o3d.geometry.PointCloud()
        pcd_slice.points = o3d.utility.Vector3dVector(intermed_list)
        o3d.io.write_point_cloud(f'test_slices/linear_slice.ply', pcd_slice)
        break
        linear_matrix.append(intermed_list)

        intermed_list = []

        a = 0

        print('done')

        

NameError: name 'ar_whole_field' is not defined

In [6]:
print(intermed_list)

[]


# I need to take the above, make it now iterate over the whole file, each element in the list linear matrix will be a 'slice'

'/home/travis/repos/radial-slicing'

In [13]:
    pcd_slice = o3d.geometry.PointCloud()
    pcd_slice.points = o3d.utility.Vector3dVector(intermed_list)
    o3d.io.write_point_cloud(f'/home/travis/linear_slice.ply', pcd_slice)

True

In [4]:
for i in ar_whole_field[:50]:
    print(i)

[   -32.90975952 -15712.09863281   1026.36804199]
[   -32.46375275 -15712.00390625   1026.51171875]
[   -35.59249878 -15713.20117188   1026.16467285]
[   -35.14556885 -15713.1640625    1026.22607422]
[   -34.69729996 -15713.24316406   1026.12268066]
[   -34.24677658 -15713.49707031   1025.77160645]
[   -33.79915619 -15713.51855469   1025.75048828]
[   -33.35292053 -15713.42382812   1025.89440918]
[   -32.90751648 -15713.27148438   1026.1204834 ]
[   -32.46298218 -15713.06152344   1026.42907715]
[   -32.01766586 -15712.90917969   1026.65527344]
[   -37.38412094 -15713.99804688   1026.41333008]
[   -36.48901367 -15714.04101562   1026.37133789]
[   -36.04077148 -15714.12011719   1026.26806641]
[   -35.59388733 -15714.08300781   1026.32946777]
[   -35.15259171 -15713.58300781   1027.0501709 ]
[   -34.69801331 -15714.18359375   1026.20507812]
[   -34.24604797 -15714.55273438   1025.68920898]
[   -33.8013382  -15714.34277344   1025.9979248 ]
[   -33.35887909 -15713.95800781   1026.55395508]


In [6]:
y_sort = sorted(ar_whole_field, key=itemgetter(1))


for i in y_sort[:300]:
    print(i)

[  -153.45756531 -15934.50097656   1018.5859375 ]
[  -152.55909729 -15934.47558594   1018.64154053]
[  -153.45536804 -15933.44433594   1018.66888428]
[  -151.6222229  -15933.40332031   1020.18743896]
[  -153.00508118 -15933.40234375   1018.73809814]
[  -152.55049133 -15933.24316406   1018.97314453]
[  -153.8946991  -15933.1953125    1019.01348877]
[  -152.09809875 -15933.14355469   1019.12493896]
[  -150.26365662 -15933.04492188   1020.72570801]
[  -151.15945435 -15933.01269531   1020.75305176]
[  -151.64363098 -15932.98535156   1019.35974121]
[  -150.69250488 -15932.50585938   1021.48388672]
[  -147.5766449  -15932.14355469   1020.64282227]
[  -151.15727234 -15931.95507812   1020.83587646]
[  -148.0163269  -15931.89453125   1020.98754883]
[  -153.43132019 -15931.80664062   1019.57971191]
[  -153.87931824 -15931.79003906   1019.59313965]
[  -149.35762024 -15931.78808594   1021.11169434]
[  -154.32733154 -15931.77441406   1019.60681152]
[  -151.63505554 -15931.75390625   1019.69116211]
