In [1]:
import numpy as np
from mpl_toolkits import mplot3d
import open3d as o3d
import glob
import os
import os.path
import statistics as stats
from operator import itemgetter

# Linear Sliceing Method
## Sort by Y

In [2]:
# Testing Ground
plant = 'plant3_bb_sim.ply'
# Slicing out a portion

# Read .ply file
pcd_whole = o3d.io.read_point_cloud(plant)
ar_whole_field = np.asarray(pcd_whole.points)

type(ar_whole_field)

numpy.ndarray

In [15]:
linear_matrix = []

intermed_list = []

a = ar_whole_field[0][0]

for i in ar_whole_field:
    print(i[0])
    if abs(i[0] - a) < 10:
        intermed_list.append(list(i))

        a = i[0]

        print(f'Building intermed list: {len(intermed_list)}')



    
    else:
        pcd_slice = o3d.geometry.PointCloud()
        pcd_slice.points = o3d.utility.Vector3dVector(intermed_list)
        o3d.io.write_point_cloud(f'/home/travis/linear_slice.ply', pcd_slice)
        break
        linear_matrix.append(intermed_list)

        intermed_list = []

        a = 0

        print('done')

        

-32.909759521484375
Building intermed list: 1
-32.46375274658203
Building intermed list: 2
-35.592498779296875
Building intermed list: 3
-35.14556884765625
Building intermed list: 4
-34.69729995727539
Building intermed list: 5
-34.24677658081055
Building intermed list: 6
-33.799156188964844
Building intermed list: 7
-33.35292053222656
Building intermed list: 8
-32.90751647949219
Building intermed list: 9
-32.462982177734375
Building intermed list: 10
-32.01766586303711
Building intermed list: 11
-37.38412094116211
Building intermed list: 12
-36.489013671875
Building intermed list: 13
-36.040771484375
Building intermed list: 14
-35.59388732910156
Building intermed list: 15
-35.152591705322266
Building intermed list: 16
-34.69801330566406
Building intermed list: 17
-34.24604797363281
Building intermed list: 18
-33.80133819580078
Building intermed list: 19
-33.35887908935547
Building intermed list: 20
-32.91131591796875
Building intermed list: 21
-32.46525573730469
Building intermed list:

In [12]:
print(intermed_list)

7, -15764.25390625, 1022.239990234375], [-10.479259490966797, -15763.986328125, 1022.6302490234375], [-10.030888557434082, -15764.0087890625, 1022.6077880859375], [-9.58258056640625, -15764.03125, 1022.5848999023438], [-155.1765594482422, -15763.75, 1021.371337890625], [-154.73765563964844, -15763.998046875, 1021.0267944335938], [-154.28321838378906, -15763.83984375, 1021.26171875], [-153.86395263671875, -15764.611328125, 1020.1728515625], [-153.4051513671875, -15764.3359375, 1020.5730590820312], [-152.95510864257812, -15764.294921875, 1020.64208984375], [-152.5007781982422, -15764.13671875, 1020.8768310546875], [-152.0572052001953, -15764.2685546875, 1020.6976928710938], [-151.60726928710938, -15764.2265625, 1020.7665405273438], [-151.16580200195312, -15764.4169921875, 1020.5050659179688], [-150.72215270996094, -15764.5498046875, 1020.3258056640625], [-150.26365661621094, -15764.275390625, 1020.7257080078125], [-149.80953979492188, -15764.1171875, 1020.960205078125], [-149.35340881347

# I need to take the above, make it now iterate over the whole file, each element in the list linear matrix will be a 'slice'

'/home/travis/repos/radial-slicing'

In [13]:
    pcd_slice = o3d.geometry.PointCloud()
    pcd_slice.points = o3d.utility.Vector3dVector(intermed_list)
    o3d.io.write_point_cloud(f'/home/travis/linear_slice.ply', pcd_slice)

True

In [4]:
for i in ar_whole_field[:50]:
    print(i)

[   -32.90975952 -15712.09863281   1026.36804199]
[   -32.46375275 -15712.00390625   1026.51171875]
[   -35.59249878 -15713.20117188   1026.16467285]
[   -35.14556885 -15713.1640625    1026.22607422]
[   -34.69729996 -15713.24316406   1026.12268066]
[   -34.24677658 -15713.49707031   1025.77160645]
[   -33.79915619 -15713.51855469   1025.75048828]
[   -33.35292053 -15713.42382812   1025.89440918]
[   -32.90751648 -15713.27148438   1026.1204834 ]
[   -32.46298218 -15713.06152344   1026.42907715]
[   -32.01766586 -15712.90917969   1026.65527344]
[   -37.38412094 -15713.99804688   1026.41333008]
[   -36.48901367 -15714.04101562   1026.37133789]
[   -36.04077148 -15714.12011719   1026.26806641]
[   -35.59388733 -15714.08300781   1026.32946777]
[   -35.15259171 -15713.58300781   1027.0501709 ]
[   -34.69801331 -15714.18359375   1026.20507812]
[   -34.24604797 -15714.55273438   1025.68920898]
[   -33.8013382  -15714.34277344   1025.9979248 ]
[   -33.35887909 -15713.95800781   1026.55395508]


In [6]:
y_sort = sorted(ar_whole_field, key=itemgetter(1))


for i in y_sort[:300]:
    print(i)

[  -153.45756531 -15934.50097656   1018.5859375 ]
[  -152.55909729 -15934.47558594   1018.64154053]
[  -153.45536804 -15933.44433594   1018.66888428]
[  -151.6222229  -15933.40332031   1020.18743896]
[  -153.00508118 -15933.40234375   1018.73809814]
[  -152.55049133 -15933.24316406   1018.97314453]
[  -153.8946991  -15933.1953125    1019.01348877]
[  -152.09809875 -15933.14355469   1019.12493896]
[  -150.26365662 -15933.04492188   1020.72570801]
[  -151.15945435 -15933.01269531   1020.75305176]
[  -151.64363098 -15932.98535156   1019.35974121]
[  -150.69250488 -15932.50585938   1021.48388672]
[  -147.5766449  -15932.14355469   1020.64282227]
[  -151.15727234 -15931.95507812   1020.83587646]
[  -148.0163269  -15931.89453125   1020.98754883]
[  -153.43132019 -15931.80664062   1019.57971191]
[  -153.87931824 -15931.79003906   1019.59313965]
[  -149.35762024 -15931.78808594   1021.11169434]
[  -154.32733154 -15931.77441406   1019.60681152]
[  -151.63505554 -15931.75390625   1019.69116211]
